news_app/news/urls.py
from django.urls import path
from .views import (
    frontpage_view,
    register_view,
    login_view,
    logout_view,
    publisher_details_view,
    add_article_view,
    delete_article_view,
    edit_article_view,
    article_details_view,
    user_profile_view,
)

app_name = "news"
urlpatterns = [
    path("", frontpage_view, name="frontpage"),

    path("register/",  register_view, name="register"),
   
    path("login/", login_view, name="login"),

    path('logout/', logout_view, name='logout'),

    path('publisher_details/<int:pk>/', publisher_details_view, name="publisher_details"),
    
    path('publisher_details/<int:pk>/add_article/', add_article_view, name='add_article'),
    
    path('delete_article/<int:pk>/', delete_article_view, name='delete_article'),

    path('edit_article/<int:pk>/', edit_article_view, name="edit_article"),

    path('article_details/<int:pk>/', article_details_view, name='article_details'),

    path('profile/<int:pk>/', user_profile_view, name='view_profile'),
]

news_app/news_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("news.urls"))
]

news_app/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=10, default='READER',)
    follows_user = models.ManyToManyField("self",
                                          related_name="followed_by",
                                          symmetrical=False, blank=True)
    follows_publisher = models.ManyToManyField("Publisher",
                                               related_name="followed_publisher",
                                               symmetrical=False, blank=True)
    working_for_publisher = models.ManyToManyField("Publisher",
                                                   related_name="working_for_publisher",
                                                   symmetrical=False, blank=True)
    def __str__(self):
        return self.user.username

def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = UserProfile(user=instance)
        user_profile.save()
        user_profile.follows_user.set([instance.userprofile.id])
        user_profile.save()

post_save.connect(create_profile, sender=User)


class Publisher(models.Model):
    name = models.CharField( max_length=255)
    def __str__(self):
        return self.name


class Article(models.Model):
    journalist = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE, blank=True)
    approved = models.BooleanField(default=False)
    def __str__(self):
        return self.title

news_app/news/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from .models import UserProfile, Article


class RegisterForm(UserCreationForm):
    USER_TYPES = (
        ('READER', 'Reader'),
        ('EDITOR', 'Editor'),
        ('JOURNALIST', 'Journalist'))
    email = forms.EmailField()
    user_type = forms.CharField(widget=forms.Select(
        choices=USER_TYPES,
        attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'user_type', 'password1', 'password2']


class LoginUserForm(AuthenticationForm):
    pass


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content',]

news_app/news/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Publisher, Article
from django.contrib.auth.models import User, Group
from .forms import RegisterForm, LoginUserForm, ArticleForm
from django.contrib.auth import login
from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.core.mail import send_mail
import tweepy
from django.conf import settings

Reader, created = Group.objects.get_or_create(name='Reader')
Journalist, created = Group.objects.get_or_create(name='Journalist')
Editor, created = Group.objects.get_or_create(name='Editor')

# Create your views here.
def frontpage_view(request):
    publisher_list = Publisher.objects.all()
    context = {'publisher_list': publisher_list}
    return render(request, "news/frontpage.html", context)


def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user_group = form.cleaned_data['user_type']
            if user_group == "EDITOR":
                my_group = Group.objects.get(name='Editor')
                new_user = form.save(commit=False)
                new_user.save()
                new_user.userprofile.user_type = user_group
                new_user.save()
                new_user = authenticate(username=form.cleaned_data['username'],
                                        password=form.cleaned_data['password1']
                                        )
                login(request, new_user)
                my_group.user_set.add(request.user)
                return redirect('news:frontpage')
            elif user_group == 'READER':
                my_group = Group.objects.get(name='Reader')
                new_user = form.save(commit=False)
                new_user.save()
                new_user.userprofile.user_type = user_group
                new_user.save()
                new_user = authenticate(username=form.cleaned_data['username'],
                                        password=form.cleaned_data['password1']
                                        )
                login(request, new_user)
                my_group.user_set.add(request.user)
                return redirect('news:frontpage')
            elif user_group == 'JOURNALIST':
                my_group = Group.objects.get(name='Journalist')
                new_user = form.save(commit=False)
                new_user.save()
                new_user.userprofile.user_type = user_group
                new_user.save()
                new_user = authenticate(username=form.cleaned_data['username'],
                                        password=form.cleaned_data['password1']
                                        )
                login(request, new_user)
                my_group.user_set.add(request.user)
                return redirect('news:frontpage')
    else:
        form = RegisterForm()
    return render(request, "news/register.html", {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = LoginUserForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('news:frontpage'))
    else:
        form = LoginUserForm()
    return render(request, "news/login.html", {'form': form})


def logout_view(request):
    logout(request)
    return redirect('news:frontpage')


def publisher_details_view(request, pk):
    user = request.user
    Journalist = user.groups.filter(name='Journalist').exists()
    editor = user.groups.filter(name='Editor').exists()
    publisher = get_object_or_404(Publisher, pk=pk)
    publisher_articles = Article.objects.filter(publisher=publisher)
    context = {
        'Journalist': Journalist,
        'editor': editor,
        'user': user,
        'publisher': publisher,
        'publisher_articles': publisher_articles,
    }
    if request.method == "POST":
        if request.user.is_authenticated:
            current_user_profile = request.user.userprofile
            action = request.POST['follow']
            if action == 'unfollow':
                current_user_profile.follows_publisher.remove(publisher.pk)
            elif action == 'follow':
                current_user_profile.follows_publisher.add(publisher.pk)
            current_user_profile.save()
    return render(request, "news/publisher_details.html", context)


def add_article_view(request, pk):
    user = request.user
    if user.has_perm('news.add_article'):
        if request.method == "POST":
            form = ArticleForm(request.POST)
            if form.is_valid():
                article = form.save(commit=False)
                article.publisher = Publisher.objects.get(pk=pk)
                article.journalist = request.user
                article.save()
                return redirect("news:frontpage")
        else:
            form = ArticleForm()
        return render(request, "news/add_article.html", {"form": form})
    else:
        return HttpResponseRedirect(reverse('news:frontpage'))
    

def update_article_view(request, pk):
    user = request.user
    if user.has_perm('news.change_article'):
        article = get_object_or_404(Article, pk=pk)
        if request.method == "POST":
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form = form.save(commit=False)
                article.approved = True
                form.save()
                return redirect("store:frontpage")
        else:
            form = ArticleForm(instance=article)
        return render(request, "news/add_article.html", {"form": form})
    else:
        return HttpResponseRedirect(reverse('news:frontpage'))
    

def delete_article_view(request, pk):
    user = request.user
    if user.has_perm('news.delete_article'):
        article = get_object_or_404(Article, pk=pk)
        article.delete()
        return redirect("news:frontpage")
    else:
        return HttpResponseRedirect(reverse('news:frontpage'))
    

def edit_article_view(request, pk):
    user = request.user
    if user.has_perm('news.change_article'):
        article = get_object_or_404(Article, pk=pk)
        if request.method == "POST":
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                article = form.save(commit=False)
                article.save()
                return redirect("news:frontpage")
        else:
            form = ArticleForm(instance=article)
        return render(request, "news/add_article.html", {"form": form})
    else:
        return HttpResponseRedirect(reverse('news:frontpage'))


def article_details_view(request, pk):
    user = request.user
    editor = user.groups.filter(name='Editor').exists()
    article = get_object_or_404(Article, pk=pk)
    context ={
        'article': article,
        'editor': editor,
    }
    if request.method == "POST":
        if request.user.is_authenticated:
            action = request.POST['approve']
            if action == 'approve':
                article.approved = True
            elif action == 'unapprove':
                article.approved = False
            article.save()
    return render(request, "news/article_details.html", context)


def user_profile_view(request, pk):
    if request.user.is_authenticated:
        profile_user = get_object_or_404(User, pk=pk)
        profile = profile_user.userprofile
        context = {
        'profile': profile, }
        if request.method == "POST":
            current_user_profile = request.user.userprofile
            action = request.POST['follow']
            if action == 'unfollow':
                current_user_profile.follows_user.remove(profile)
            elif action == 'follow':
                current_user_profile.follows_user.add(profile)
            current_user_profile.save()

        return render(request, "news/profile.html", context)


@receiver(post_save, sender=Article,)
def send_email(sender, instance: Article, **kwargs):
    article = Article.objects.get(pk=instance.pk)
    journalist = article.journalist
    publisher = article.publisher
    if article.approved == True:
        journalist_sub_users = User.objects.get(follows_user=journalist)
        for user in journalist_sub_users:
            user_email = user.email
            send_mail(
                'New artricle',
                'A new article has been published',
                'news_app@gmail.com',
                [f'{user_email}'],
            )
        publisher_sub_user = User.objects.get(follows_publisher=publisher)
        for user in publisher_sub_user:
            user_email = user.email
            send_mail(
                'New artricle',
                'A new article has been published',
                'news_app@gmail.com',
                [f'{user_email}'],
            )


@receiver(post_save, sender=Article,)
def send_tweet(sender, instance: Article, **kwargs):
    article = Article.objects.get(pk=instance.pk)
    if article.approved == True:
        journalist = article.journalist
        auth = tweepy.OAuth1UserHandler(settings.API_KEY, settings.API_KEY_SECRET)
        auth.set_access_token(settings.ACCESS_TOKEN, settings.ACCESS_TOKEN_SECRET)
        api = tweepy.API(auth)
        api.update_status(f'{article.title} has been posted by {journalist}')

news_app/news/templates/news/add_article.html
{% extends "news/base.html" %}
{% block title %}
    Add Article
{% endblock title %}
{% block content %}
    <h1>Please Add Your Article</h1>
    <form method="POST">
        {% csrf_token %}
            {{ form.as_p }}
        <button type="submit" class="btn">Submit</button>
    </form>
{% endblock content %}

news_app/news/templates/news/article_details.html
{% extends "news/base.html" %}
{% block title %}
    {{ article.title  }}
{% endblock title %}
{% block content %}
    <h1>{{ article.title }}</h1>
    <h2>Content:</h2>
    {{ article.content }}
    
    <form method=POST>
        {% csrf_token %}
        {% if article.publisher in user.userprofile.working_for_publisher.all and editor == True %}
            {%if article.approved == False %}
                <button class="btn" name ="approve" value = "approve" type='sumbit'>Approve</button>
            {% else %}
                <button class="btn" name ="approve" value = "unapprove" type='sumbit'>Unapprove</button>
            {% endif %}
       
        {% endif %}
    </form>
{% endblock content %}

news_app/news/templates/news/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <title>{% block title %}FrontPage{% endblock %} | Newsapp</title>
        <link rel="stylesheet" href="{% static 'core/styles.css' %}" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    </head>
    <body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
        <nav>
            <div class="navbutton">
                <a href="/">Frontpage</a>
                |
                <a href="{% url 'news:register' %}">Register</a>
                |
                <a href="{% url 'news:login' %}">Login</a>
                |
                <a href="{% url 'news:logout' %}">Logout</a>
                |
                Currently Logged in as {{ user }}
            </div>
        </nav>
        {% block content %}
        {% endblock content %}
        <footer>
        The news app for all your best independat journalist
        </footer>
    </body>
</html>

news_app/news/templates/news/frontpage.html
{% extends "news/base.html" %}
{% block title %}
    FrontPage
{% endblock %}
{% block content %}
    This is the frontpage<br>
    {% for publisher in publisher_list %}
        <a href="{% url 'news:publisher_details' pk=publisher.pk %}">{{ publisher.name }}</a>
    {% endfor %}
{% endblock content %}

news_app/news/templates/news/login.html
{% extends "news/base.html" %}
{% block title %}
    LOGIN
{% endblock title %}
{% block content %}
    <h1>LOGIN HERE</h1>
    <form method="POST">
        {% csrf_token %}
            {{ form.as_p }}
        <button type="submit" class="btn">Login</button>
    </form>
{% endblock content %}

news_app/news/templates/news/profile.html
{% extends "news/base.html" %}
{% block title %}
    {{ profile }} profile
{% endblock %}
{% block content %}
    This is the profile of {{ profile }}<br>
    <form method=POST>
        {% csrf_token %}
        {% if profile in user.userprofile.follows_user.all %}
            <button class="btn" name ="follow" value = "unfollow" type='sumbit'>Unfollow {{profile}}</button>
        {% else %}
            <button class="btn" name ="follow" value = "follow" type='sumbit'>follow {{profile}}</button>
       
        {% endif %}
    </form>

{% endblock content %}

news_app/news/templates/news/publisher_details.html
{% extends "news/base.html" %}
{% block title %}
    {{ publisher.name }}
{% endblock title %}
{% block content %}
    This is the details page for {{ publisher.name }}<br>
    {% if publisher in user.userprofile.working_for_publisher.all and Journalist == True %}
    <a href="{% url 'news:add_article' pk=publisher.pk %}">Add Article</a>
    {% endif %}
    <h2>Articles published by {{ publisher.name }}:</h2>
        {% for article in publisher_articles %}
            {% if editor == True and publisher in user.userprofile.working_for_publisher.all or article.approved == True or article.journalist == user %}
                <a href="{% url 'news:article_details' pk=article.pk %}"><h3>{{ article.title }}</h3></a>
                by <a href="{% url 'news:view_profile' pk=article.journalist.pk %}">{{ article.journalist }}</a><br>
                {% if article.journalist == user %}
                    <a href="{% url 'news:edit_article' pk=article.pk %}">edit</a>
                    <a href="{% url 'news:delete_article' pk=article.pk %}">Delete</a>
                {% endif %}
                {% if editor == True and publisher in user.userprofile.working_for_publisher.all %}
                    <a href="{% url 'news:edit_article' pk=article.pk %}">edit</a>
                    <a href="{% url 'news:delete_article' pk=article.pk %}">Delete</a>
                {% endif %}
            {% endif %}
        {% endfor %}
    <form method=POST>
        {% csrf_token %}
        {% if publisher in user.userprofile.follows_publisher.all %}
            <button class="btn" name ="follow" value = "unfollow" type='sumbit'>Unfollow {{publisher.name}}</button>
        {% else %}
            <button class="btn" name ="follow" value = "follow" type='sumbit'>follow {{publisher.name}}</button>
       
        {% endif %}
    </form>
{% endblock content %}

news_app/news/templates/news/register.html
{% extends "news/base.html" %}
{% block title %}
    Register
{% endblock title %}
{% block content %}
    <h1>REGISTER</h1>
    <form method="POST">
        {% csrf_token %}
            {{ form.as_p }}
        <button type="submit" class="btn">Register</button>
    </form>
{% endblock content %}